---
- name: create sssignal.conf
  template:
    src: templates/sssignal.conf
    dest: /etc/nginx/conf.d/sssignal.conf

- name: remove default.conf
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: create server.crt
  template:
    src: templates/server.crt
    dest: /etc/nginx/server.crt

- name: create server.key
  template:
    src: templates/server.key
    dest: /etc/nginx/server.key

- name: start nginx
  service:
    name: nginx
    state: started
  
- name: enable nginx
  service:
    name: nginx
    enabled: yes
